# -*- coding: utf-8 -*-
"""Gridsentinel_app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XD6sOVookTvW7y967irQpsyXsLRAtklF

# CELL 1 — Install dependencies
# streamlit = dashboard
# pandapower = IEEE-14 grid + state estimation
# numpy/pandas = math + tables
"""

!pip install -q streamlit pandapower numpy pandas

"""# CELL 2 — Create gridsentinel_app.py
# This writes the full app file (attack → trust → isolation → recovery → decision)
"""

app_code = r'''
import streamlit as st
import pandapower as pp
import pandapower.networks as pn
import numpy as np
import pandas as pd
from copy import deepcopy

st.set_page_config(page_title="GridSentinel AI", page_icon="🛡️", layout="wide")

def run_gridsentinel():
    np.random.seed(None)

    net = pn.case14()
    pp.runpp(net)

    # Clean voltages + light noise
    clean = {}
    for b in net.bus.index:
        base = float(net.res_bus.at[b, "vm_pu"])
        clean[b] = float(np.clip(base + np.random.normal(0, 0.0015), 0.92, 1.08))

    meas = deepcopy(clean)

    # Strong single-sensor FDIA
    attack_bus = int(np.random.choice(list(net.bus.index)))
    true_v = clean[attack_bus]
    direction = np.random.choice([-1.0, 1.0])
    magnitude = np.random.uniform(0.12, 0.30)
    fake_v = float(np.clip(true_v + direction * magnitude, 0.80, 1.30))
    meas[attack_bus] = fake_v

    # -------- Trust (no true value) --------
    # Use robust stats, but make threshold stricter so fewer false positives
    vals = np.array(list(meas.values()), dtype=float)
    med = float(np.median(vals))
    mad = float(np.median(np.abs(vals - med))) + 1e-6

    trust = {}
    for b in net.bus.index:
        z = abs(meas[b] - med) / (1.4826 * mad)
        # stricter mapping => only clear outliers drop hard
        t = max(0.0, 100.0 * (1.0 - z / 6.0))
        trust[b] = float(t)

    # Primary isolation: lowest trust sensor + any extremely low scores
    sorted_buses = sorted(trust.keys(), key=lambda b: trust[b])
    primary = sorted_buses[0]

    THRESHOLD = 35.0  # stricter than before
    isolated = [b for b, t in trust.items() if t < THRESHOLD]

    # Always include the clearest outlier
    if primary not in isolated:
        isolated.append(primary)

    # Keep isolation focused (max 3) for cleaner demo behavior
    isolated = sorted(isolated, key=lambda b: trust[b])[:3]

    # Reconstruction from trusted only
    trusted_vals = [meas[b] for b in meas if b not in isolated]
    fill = float(np.median(trusted_vals)) if trusted_vals else med

    recon = deepcopy(meas)
    for b in isolated:
        recon[b] = fill

    # State estimation
    net2 = deepcopy(net)
    net2.measurement.drop(net2.measurement.index, inplace=True)
    for b in net2.bus.index:
        pp.create_measurement(net2, meas_type="v", element_type="bus",
                              value=recon[b], std_dev=0.01, element=b)
        pp.create_measurement(net2, meas_type="p", element_type="bus",
                              value=float(net.res_bus.at[b, "p_mw"]), std_dev=0.08, element=b)
        pp.create_measurement(net2, meas_type="q", element_type="bus",
                              value=float(net.res_bus.at[b, "q_mvar"]), std_dev=0.08, element=b)

    success = False
    est_v = None
    try:
        success = bool(pp.estimation.estimate(net2, algorithm="wls"))
        if success and attack_bus in net2.res_bus_est.index:
            est_v = float(net2.res_bus_est.at[attack_bus, "vm_pu"])
    except Exception:
        success = False

    # Decision confidence
    total = len(trust)
    trusted_n = total - len(isolated)
    trust_ratio = trusted_n / total

    recovery_q = 0.7
    if est_v is not None:
        err = abs(recon[attack_bus] - est_v)
        recovery_q = float(max(0.0, 1.0 - err / 0.10))

    # Bonus if the true attack bus was isolated
    hit_bonus = 0.12 if attack_bus in isolated else 0.0
    isolation_penalty = 0.05 * max(0, len(isolated) - 1)

    conf = 100.0 * (
        0.42 * trust_ratio +
        0.30 * (1.0 if success else 0.2) +
        0.28 * recovery_q
        + hit_bonus
        - isolation_penalty
    )
    conf = float(np.clip(conf, 8, 97))

    if success and conf >= 80:
        rec, level = "PROCEED WITH RECOVERED STATE", "green"
    elif success and conf >= 58:
        rec, level = "PROCEED WITH CAUTION", "yellow"
    else:
        rec, level = "REQUIRE FURTHER VALIDATION", "red"

    return {
        "attack_bus": attack_bus,
        "true_v": true_v,
        "fake_v": fake_v,
        "trust": trust,
        "isolated": isolated,
        "recon_v": recon[attack_bus],
        "est_v": est_v,
        "success": success,
        "conf": conf,
        "trusted_n": trusted_n,
        "sus_n": len(isolated),
        "total": total,
        "rec": rec,
        "level": level,
        "threshold": THRESHOLD,
        "primary": primary,
    }


if "res" not in st.session_state:
    st.session_state.res = None

st.markdown("# 🛡️ GridSentinel AI")
st.markdown("### Trust-Aware Decision Layer for Resilient Smart Grid Operation")
st.caption("Random FDIA · Trust without true values · Isolation → Reconstruction → Operational decision")

c1, c2 = st.columns(2)
with c1:
    go = st.button("⚡ Run Full Pipeline", type="primary", use_container_width=True)
with c2:
    if st.button("🔄 New Random Scenario", use_container_width=True):
        st.session_state.res = None
        st.rerun()

if go:
    with st.spinner("Running attack → trust → isolation → reconstruction → decision..."):
        st.session_state.res = run_gridsentinel()

r = st.session_state.res
if r is None:
    st.info("Press **Run Full Pipeline** to start.")
    st.stop()

sid = r["attack_bus"] + 1

st.markdown("---")
st.markdown("## 📊 System Overview")
st.write(f"- **Grid:** IEEE-14 Bus")
st.write(f"- **Sensors:** {r['total']}")
st.write(f"- **Trusted:** {r['trusted_n']}")
st.write(f"- **Isolated / Suspicious:** {r['sus_n']}")

st.markdown("## 🚨 FDIA Attack Detected")
st.write(f"- **Target Sensor:** Sensor {sid:02d}")
st.write(f"- **True Voltage:** {r['true_v']:.4f} p.u.")
st.write(f"- **Injected (Fake):** {r['fake_v']:.4f} p.u.")
st.error(f"Sensor {sid:02d} compromised. Detection did **not** use the true clean value.")

st.markdown("## 🔐 Sensor Trust Scores")
rows = []
for b, t in r["trust"].items():
    status = "ISOLATED" if b in r["isolated"] else ("LOW" if t < r["threshold"] else "TRUSTED")
    rows.append({"Sensor": f"S{b+1:02d}", "Trust %": round(t, 1), "Status": status})
st.table(pd.DataFrame(rows))
st.caption("Robust median/MAD trust. No oracle true values used.")

st.markdown("## 🔧 Isolation & Reconstruction")
st.warning("Isolated: " + ", ".join([f"S{b+1:02d}" for b in r["isolated"]]))
st.write(f"- **Attacked Value:** {r['fake_v']:.4f}")
st.write(f"- **Reconstructed:** {r['recon_v']:.4f}")
st.write(f"- **Estimated (WLS):** {r['est_v']:.4f}" if r["est_v"] is not None else "- **Estimated (WLS):** N/A")

st.markdown("## 🎯 Operational Decision")
st.write(f"- **Decision Confidence:** **{r['conf']:.1f}%**")
st.write(f"- **State Re-estimation:** {'SUCCESS' if r['success'] else 'FAILED'}")

if r["level"] == "green":
    st.success(f"### 🟢 {r['rec']}")
    st.write("Recovered state is sufficiently reliable for continued operation.")
elif r["level"] == "yellow":
    st.warning(f"### 🟡 {r['rec']}")
    st.write("State recovered with residual uncertainty. Operator awareness recommended.")
else:
    st.error(f"### 🔴 {r['rec']}")
    st.write("Confidence too low for automatic operational decision.")

st.markdown("---")
st.caption("GridSentinel AI · Trust-Aware Resilience Prototype · IEEE-14 + pandapower WLS")
'''

with open("app.py", "w") as f:
    f.write(app_code)

print("✅ app.py updated for ~9/10")

"""# CELL 3 — Start Streamlit server on port 8501 (background)

# CELL 4 — Public link (Cloudflare tunnel)
# Open the https://....trycloudflare.com link in a new tab
"""

import subprocess, time, os


os.system("pkill -f streamlit || true")
time.sleep(2)

subprocess.Popen([
    "streamlit", "run", "app.py",
    "--server.port", "8501",
    "--server.headless", "true"
])
time.sleep(6)
print("✅ Streamlit running")

# Cloudflare tunnel
!wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -O cloudflared
!chmod +x cloudflared
!./cloudflared tunnel --url http://localhost:8501